"""test-drive bookings

Revision ID: 16909bf374c8
Revises: f28b08ce30b2
Create Date: 2026-05-29 21:52:17.129588
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '16909bf374c8'
down_revision: str | None = 'f28b08ce30b2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_drive_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('slot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('requested', 'confirmed', 'declined', 'cancelled', name='test_drive_status'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_drive_bookings_listing_id'), 'test_drive_bookings', ['listing_id'], unique=False)
    op.create_index(op.f('ix_test_drive_bookings_requester_id'), 'test_drive_bookings', ['requester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_drive_bookings_requester_id'), table_name='test_drive_bookings')
    op.drop_index(op.f('ix_test_drive_bookings_listing_id'), table_name='test_drive_bookings')
    op.drop_table('test_drive_bookings')
    # ### end Alembic commands ###
