"""deposits (escrow)

Revision ID: 3633e5a72a19
Revises: 16909bf374c8
Create Date: 2026-05-29 22:03:41.562240
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3633e5a72a19'
down_revision: str | None = '16909bf374c8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('amount_eur_cents', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('held', 'released', 'refunded', 'failed', name='deposit_status'), nullable=False),
    sa.Column('provider_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposits_buyer_id'), 'deposits', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_deposits_listing_id'), 'deposits', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deposits_listing_id'), table_name='deposits')
    op.drop_index(op.f('ix_deposits_buyer_id'), table_name='deposits')
    op.drop_table('deposits')
    # ### end Alembic commands ###
