"""ev fields on vehicles

Revision ID: 4746362ecd97
Revises: 3633e5a72a19
Create Date: 2026-05-29 22:19:53.259499
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4746362ecd97'
down_revision: str | None = '3633e5a72a19'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('battery_kwh', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('range_km', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('charge_power_kw', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('charge_port', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'charge_port')
    op.drop_column('vehicles', 'charge_power_kw')
    op.drop_column('vehicles', 'range_km')
    op.drop_column('vehicles', 'battery_kwh')
    # ### end Alembic commands ###
